### ISSUE TITLE
无法获取封顶价。

### ISSUE THREAD

**Issue by rqx110** [Calvin92/jd-paimai-plugin#1]
`this.originPrice  = $(".cost del").text();  //代码已失效`

**Comment by Calvin92** [comment]
thank u for your pr

**Comment by rqx110** [comment]
自动抢拍的时候很容易会被系统返回1000000的价格，不知有什么好办法没？

**Comment by Calvin92** [comment]
Fixed。。  你可以pull下来看看新的代码，为了测试可用性，刚抢拍了个没必要的登山包。。
使用的时候，建议调个200ms左右的调节时间～
thx
